### ISSUE TITLE
Create a plunker to show what this does?

### ISSUE THREAD

**Issue by jmpreston** [pjlamb12/angular-tag-select#24]
I'm trying to figure out if your solution meets my app's needs and going through the code.  A plunker would really help!

Great work!  Thanks!

**Comment by plambhsa** [comment]
@svstartuplab Hey! Check out ats.oss.prestonlamb.com for an example.

**Comment by jmpreston** [comment]
Great, thanks!  I didn't see this in the read file.

**Comment by plambhsa** [comment]
Sorry, it's not in the README yet, but is in the package.json as homepage.

**Comment by pjlamb12** [comment]
@svstartuplab I'm going to close this issue and create a new one to add the demo page to the README
